name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:name: Greetings

on:
  pull_request_target:
  issues:
    types:
      - opened
      - edited

jobs:
  greeting:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version you need

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Greet New Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to Abeg Help! 🎉 Please feel free to ask questions, contribute if you can. To assign this issue to yourself, kindly reply to this issue `.take`. We're here to help!"
          pr-message: "Thanks for your contribution! 🙌 We appreciate your pull request. Kindly request for a review, and our team will review it as soon as possible. If you have any questions or need assistance, please don't hesitate to ask."

          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to Abeg Help! 🎉 Please feel free to ask questions, contribute if you can, To assign this issue to yourself, kindly reply to this issue `.take`. We're here to help!"
          pr-message: "Thanks for your contribution! 🙌 We appreciate your pull request. Kindly request for a review in and Our team will review it as soon as possible. If you have any questions or need assistance, please don't hesitate to ask."
