name: Greetings

on:
  pull_request_target:
  issues:
    types:
      - opened
      - edited

jobs:
  greeting:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Clean Docker Environment
        run: |
          docker rm -f $(docker ps -a -q)
          docker rmi -f $(docker images -q)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Greet New Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to Abeg Help! 🎉 Please feel free to ask questions, contribute if you can. To assign this issue to yourself, kindly reply to this issue `.take`. We're here to help!"
          pr-message: "Thanks for your contribution! 🙌 We appreciate your pull request. Kindly request for a review, and our team will review it as soon as possible. If you have any questions or need assistance, please don't hesitate to ask."
